[toolchain]
package_manager = "yarn"

[toolchain]
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrowfloor = "4gjmWmuanYNZTsU1vXnUSUsphL9BYBNSkh6UoU5ym9i4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
