[programs.localnet]
escrowfloor = "4gjmWmuanYNZTsU1vXnUSUsphL9BYBNSkh6UoU5ym9i4"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
